### ISSUE TITLE
Schedule for V3.0

### ISSUE THREAD

**Issue by Andy79881** [AxxAxx/AxxSolder#37]
Is there any rough schedule available for V3.0 release? I think about waiting for the V3.0 release.

**Comment by AxxAxx** [comment]
Hi! 

I have went through a "alpha" version of AxxSolder 3.0 now for a while. If works well except that there could in some cases be high voltage spikes due to cable inductance while hot-plugging AxxSolder that could eventually kill the DC-DC controller. 

I have ordered new PCBs with an updated DC-DC converter that should be able to handle a the high transient voltage when hot-plugging.


I hope these PCBs arrive within 2 weeks and I can do the final testing and then release 3.0
